import type { TitleDecision, TitleLayerOverride, TitleLayoutOverride } from "../../project/contracts";
import { editLayerLayout, editLayerOverride, layerForParameter, layerText, resetLayerPosition, resetLayerStyle, resolveLayerLayout, titleLayers } from "../../templates/layers";

const field = "w-full rounded border border-line bg-canvas px-2 py-1.5 text-xs text-ink";
const label = "block space-y-1 text-[10px] text-muted";
const color = (value: string | undefined, fallback: string) => /^#[0-9a-f]{6}$/i.test(value ?? "") ? value! : fallback;

function DraftInput({ value, onCommit, type = "text", min, max, step, ariaLabel }: { value: string | number; onCommit: (value: string) => void; type?: "text" | "number"; min?: number; max?: number; step?: number; ariaLabel: string }) {
  return <input aria-label={ariaLabel} className={field} defaultValue={String(value)} key={`${ariaLabel}:${value}`} max={max} min={min} onBlur={event => { if (event.currentTarget.value !== String(value)) onCommit(event.currentTarget.value); }} onKeyDown={event => { if (event.key === "Enter") event.currentTarget.blur(); if (event.key === "Escape") { event.currentTarget.value = String(value); event.currentTarget.blur(); } }} step={step} type={type}/>;
}

export function TitleLayerInspector({ title, selectedLayerId, onSelectLayer, onChange, aspectRatio }: { title: TitleDecision; selectedLayerId: string | null; onSelectLayer: (id: string) => void; onChange: (title: TitleDecision) => void; aspectRatio: number }) {
  const layers = titleLayers(title);
  const primaryId = layerForParameter(title, "text")?.layerId ?? layers.find(item => item.editable)?.layerId;
  const selected = layers.find(item => item.layerId === selectedLayerId) ?? layers.find(item => item.layerId === primaryId);
  if (!selected) return null;
  const override = title.layerOverrides?.[selected.layerId] ?? {};
  const layout = resolveLayerLayout(title, selected.layerId, aspectRatio);
  const isPrimary = selected.layerId === primaryId;
  const set = (patch: Partial<TitleLayerOverride>) => onChange(editLayerOverride(title, selected.layerId, patch));
  const setLayout = (patch: TitleLayoutOverride) => onChange(editLayerLayout(title, selected.layerId, aspectRatio, patch));
  const number = (value: string, fallback: number) => Number.isFinite(Number(value)) ? Number(value) : fallback;
  const numeric = (name: string, value: number, update: (value: number) => void, min?: number, max?: number, step = 1) => <label className={label}>{name}<DraftInput ariaLabel={name} type="number" min={min} max={max} step={step} value={value} onCommit={next => update(number(next, value))}/></label>;
  return <div className="space-y-3">
    <div><h4 className="mb-1 font-semibold text-cyan">Capas</h4><div className="space-y-1">{layers.map(layer => <button aria-pressed={selected.layerId === layer.layerId} className={`flex w-full items-center justify-between rounded border px-2 py-1.5 text-left text-[10px] ${selected.layerId === layer.layerId ? "border-cyan bg-cyan/10 text-ink" : "border-line text-muted hover:border-cyan"}`} key={layer.layerId} onClick={() => onSelectLayer(layer.layerId)} type="button"><span>{layer.role}</span><span>{layer.editable ? "T" : "🔒"}</span></button>)}</div></div>
    {!selected.editable ? <p className="text-[10px] text-muted">Esta capa decorativa está bloqueada por el diseño de la plantilla.</p> : <>
      <label className={label}>Texto<textarea aria-label={`Texto de ${selected.role}`} className={field} key={`${title.id}:${selected.layerId}`} onBlur={event => { const next = event.target.value; if (next !== layerText(title, selected.layerId)) set({ text: next }); }} onKeyDown={event => { if (event.key === "Escape") { event.currentTarget.value = layerText(title, selected.layerId); event.currentTarget.blur(); } }} defaultValue={layerText(title, selected.layerId)} rows={2}/></label>
      <div className="grid grid-cols-2 gap-2"><label className={label}>Fuente<select className={field} onChange={event => { const font=event.target.value as TitleLayerOverride["font"]; set({ font, fontWeight: font==="Instrument Serif"?400:700, italic: font==="Instrument Serif" }); }} value={override.font ?? title.font}><option>Inter</option><option>Instrument Serif</option></select></label><label className={label}>Peso<select className={field} disabled={(override.font ?? title.font)==="Instrument Serif"} onChange={event => set({ fontWeight: Number(event.target.value) })} value={(override.font ?? title.font)==="Instrument Serif"?400:override.fontWeight ?? title.fontWeight}>{((override.font ?? title.font)==="Instrument Serif"?[400]:[400,500,600,700,800,900]).map(weight => <option key={weight} value={weight}>{weight}</option>)}</select></label></div>
      <div className="flex gap-2"><button aria-pressed={(override.font ?? title.font)==="Instrument Serif"} className="rounded border border-line px-2 py-1 aria-pressed:border-cyan disabled:opacity-50" disabled type="button" title="Instrument Serif incluye cursiva; Inter cursiva no está instalada">Cursiva</button><button aria-pressed={!!override.underline} className="rounded border border-line px-2 py-1 aria-pressed:border-cyan" onClick={() => set({ underline: !override.underline })} type="button">Subrayado</button></div>
      <label className={label}>Caja<select className={field} onChange={event => set({ case: event.target.value as TitleLayerOverride["case"] })} value={override.case ?? "original"}><option value="original">Original</option><option value="upper">MAYÚSCULAS</option><option value="lower">minúsculas</option><option value="title">Título</option></select></label>
      <div className="grid grid-cols-2 gap-2">{numeric("Tamaño de fuente", override.fontSize ?? title.fontSize, value => set({ fontSize: Math.max(8, Math.min(240, value)) }), 8, 240)}<label className={label}>Color<div className="flex gap-1"><input aria-label="Selector de color" className="h-8 w-9 shrink-0 rounded border border-line bg-canvas" onChange={event => set({ fill: event.target.value })} type="color" value={color(override.fill, isPrimary ? title.color : title.accentColor)}/><DraftInput ariaLabel="Color HEX" value={override.fill ?? (isPrimary ? title.color : title.accentColor)} onCommit={value => { if (/^#[0-9a-f]{6}$/i.test(value)) set({ fill: value.toUpperCase() }); }}/></div></label></div>
      <label className={label}>Alineación<select className={field} onChange={event => set({ alignment: event.target.value as TitleLayerOverride["alignment"] })} value={override.alignment ?? title.alignment}><option value="left">Izquierda</option><option value="center">Centro</option><option value="right">Derecha</option></select></label>
      <div className="grid grid-cols-2 gap-2">{numeric("Espaciado letras", override.letterSpacing ?? 0, value => set({ letterSpacing: Math.max(-10, Math.min(40, value)) }), -10, 40, 0.1)}{numeric("Interlineado", override.lineHeight ?? title.lineHeight, value => set({ lineHeight: Math.max(0.5, Math.min(3, value)) }), 0.5, 3, 0.05)}</div>
      <div className="grid grid-cols-2 gap-2">{numeric("Contorno", override.strokeWidth ?? 0, value => set({ strokeWidth: Math.max(0, Math.min(12, value)) }), 0, 12, 0.1)}<label className={label}>Color contorno<input aria-label="Color contorno" className={`${field} h-9 p-1`} onChange={event => set({ strokeColor: event.target.value })} type="color" value={color(override.strokeColor, "#000000")}/></label></div>
      <details className="space-y-2 rounded border border-line p-2"><summary className="cursor-pointer text-[10px] font-semibold">Sombra y brillo</summary><div className="grid grid-cols-2 gap-2 pt-2">{numeric("Desenfoque sombra", override.shadowBlur ?? 0, value => set({ shadowBlur: Math.max(0, Math.min(100, value)) }), 0, 100)}{numeric("Desplazamiento X", override.shadowOffsetX ?? 0, value => set({ shadowOffsetX: value }), -100, 100)}{numeric("Desplazamiento Y", override.shadowOffsetY ?? 0, value => set({ shadowOffsetY: value }), -100, 100)}{numeric("Intensidad brillo", override.glowIntensity ?? 0, value => set({ glowIntensity: Math.max(0, Math.min(100, value)) }), 0, 100)}</div><div className="grid grid-cols-2 gap-2"><label className={label}>Color sombra<input aria-label="Color sombra" className={`${field} h-9 p-1`} onChange={event => set({ shadowColor: event.target.value })} type="color" value={color(override.shadowColor, "#000000")}/></label><label className={label}>Color brillo<input aria-label="Color brillo" className={`${field} h-9 p-1`} onChange={event => set({ glowColor: event.target.value })} type="color" value={color(override.glowColor, title.accentColor)}/></label></div></details>
      {numeric("Opacidad", override.opacity ?? 1, value => set({ opacity: Math.max(0, Math.min(1, value)) }), 0, 1, 0.05)}
      <div className="border-t border-line pt-2"><h4 className="mb-2 font-semibold text-cyan">Transformación · {aspectRatio < 0.8 ? "Vertical" : aspectRatio < 1.15 ? "Cuadrado" : aspectRatio < 1.55 ? "Clásico" : aspectRatio >= 2.15 ? "Panorámico" : "Horizontal"}</h4><div className="grid grid-cols-2 gap-2">{numeric("Posición X %", Math.round(layout.x * 1000) / 10, value => setLayout({ x: value / 100 }), 0, 100, 0.1)}{numeric("Posición Y %", Math.round(layout.y * 1000) / 10, value => setLayout({ y: value / 100 }), 0, 100, 0.1)}{numeric("Escala", layout.scale, value => setLayout({ scale: value }), 0.25, 4, 0.01)}{numeric("Rotación °", layout.rotation, value => setLayout({ rotation: value }), -180, 180)}{numeric("Ancho máximo %", Math.round(layout.maxWidth * 100), value => setLayout({ maxWidth: value / 100 }), 10, 95)}</div></div>
      <div className="flex flex-wrap gap-2"><button className="rounded border border-line px-2 py-1 hover:border-cyan" onClick={() => onChange(resetLayerPosition(title, selected.layerId, aspectRatio))} type="button">Restablecer posición</button><button className="rounded border border-line px-2 py-1 hover:border-cyan" onClick={() => onChange(resetLayerStyle(title, selected.layerId))} type="button">Restablecer estilo</button></div>
    </>}
  </div>;
}
